// Generated by CoffeeScript 1.7.1

/*
Module dependencies.路由配置
 */

(function() {
  var MongoStore, app, express, flash, growl, http, partials, path, routes, settings;

  express = require("express");

  http = require("http");

  path = require("path");

  routes = require("./routes");

  MongoStore = require("connect-mongo")(express);

  settings = require("./settings");

  partials = require("express-partials");

  flash = require("connect-flash");

  growl = require("growl");

  app = express();

  app.use(express["static"](path.join(__dirname, "public")));

  if ("development" === app.get("env")) {
    app.use(express.errorHandler());
  }

  app.use(express.methodOverride());

  app.use(express.bodyParser({
    keepExtensions: true,
    uploadDir: path.join(__dirname, "public/temp")
  }));

  app.set("views", __dirname + "/views");

  app.set("view engine", "jade");

  app.configure("dev", function() {
    console.log("dev");
    app.use(partials());
    app.use(express.urlencoded());
    app.use(express.json());
    app.use(express.logger("dev"));
    app.use(express.favicon());
    app.set("port", process.env.PORT || 3000);
    app.set("views", path.join(__dirname, "views"));
    app.set("views", __dirname + "/views");
    app.set("view engine", "jade");
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser());
    app.use(express.session({
      secret: settings.cookieSecret,
      store: new MongoStore({
        db: settings.db
      })
    }));
    app.use(express["static"](__dirname + "/public"));
    app.use(flash());
  });

  require("./routes/index")(app);

  app.use(require("connect-assets")());

  http.createServer(app).listen(app.get("port"), function() {
    growl("node app.js 重启成功！");
    console.log("Express server listening on port " + app.get("port"));
  });

  module.exports = {
    cookieSecret: "fanyouyinli",
    db: "fanyouyinli",
    host: "localhost",
    port: 27017
  };

  module.exports = {
    cookieSecret: "fanyouyinli",
    db: "fanyouyinli",
    host: "localhost"
  };

}).call(this);
